services:
  - type: web
    name: contexthire
    env: python
    buildCommand: "sh build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.12
